In [1]:
import numpy as np

# 1. Jednowymiarowa tablica z pierwszymi 10 dodatnimi liczbami całkowitymi

In [2]:
wektor_10 = np.arange(1, 11)
print("Wektor z pierwszymi 10 dodatnimi liczbami całkowitymi:", wektor_10)

Wektor z pierwszymi 10 dodatnimi liczbami całkowitymi: [ 1  2  3  4  5  6  7  8  9 10]


# 2.  Dwuwymiarowa tablica 3x3 wypełniona zerami

In [3]:
macierz_3x3 = np.zeros((3, 3))
print("Macierz 3x3 wypełniona zerami:\n", macierz_3x3)

Macierz 3x3 wypełniona zerami:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# 3. Utworzenie tablicy 5x5 wypełnionej losowymi liczbami całkowitymi z zakresu od 1 do 10

In [4]:
macierz_5x5 = np.random.randint(1, 11, (5, 5))
print("Macierz 5x5 wypełniona losowymi liczbami całkowitymi od 1 do 10:\n", macierz_5x5)

Macierz 5x5 wypełniona losowymi liczbami całkowitymi od 1 do 10:
 [[ 9  2  7  5  2]
 [ 5  7  1  1  8]
 [10  9  5  7 10]
 [ 8  8  6  9  2]
 [ 7  6  9  2  6]]


# 4. Tablica 4x4 wypełniona losowymi liczbami rzeczywistymi od 0 do 1

In [5]:
macierz_4x4 = np.random.rand(4, 4)
print("Macierz 4x4 wypełniona losowymi liczbami rzeczywistymi od 0 do 1:\n", macierz_4x4)

Macierz 4x4 wypełniona losowymi liczbami rzeczywistymi od 0 do 1:
 [[0.48476955 0.01341529 0.20114074 0.14848266]
 [0.66264006 0.73569257 0.90112856 0.535683  ]
 [0.79804708 0.56963084 0.42723937 0.10904732]
 [0.96282636 0.16760569 0.04152976 0.21900337]]


# 5. Operacje na dwóch jednowymiarowych tablicach

Dwie jednowymiarowe tablice o rozmiarze 5 z losowymi liczbami całkowitymi od 1 do 10

In [6]:
wektor_5_1 = np.random.randint(1, 11, 5)
wektor_5_2 = np.random.randint(1, 11, 5)

Operacje arytmetyczne

In [7]:
dodawanie = wektor_5_1 + wektor_5_2
odejmowanie = wektor_5_1 - wektor_5_2
mnożenie = wektor_5_1 * wektor_5_2

print("Wektor 1:", wektor_5_1)
print("Wektor 2:", wektor_5_2)
print("Dodawanie:", dodawanie)
print("Odejmowanie:", odejmowanie)
print("Mnożenie:", mnożenie)

Wektor 1: [10  4  7  6  3]
Wektor 2: [ 4 10 10  5  7]
Dodawanie: [14 14 17 11 10]
Odejmowanie: [ 6 -6 -3  1 -4]
Mnożenie: [40 40 70 30 21]


# 6. Iloczyn skalarny dwóch wektorów

Dwa wektory o rozmiarze 7 z losowymi liczbami

In [8]:
wektor_7_1 = np.random.randint(1, 11, 7)
wektor_7_2 = np.random.randint(1, 11, 7)

Iloczyn skalarny

In [9]:
iloczyn_skalarny = np.dot(wektor_7_1, wektor_7_2)
print("Iloczyn skalarny:", iloczyn_skalarny)

Iloczyn skalarny: 192


# 7. Mnożenie dwóch macierzy o rozmiarach 2x2 i 2x3

Dwie macierze o rozmiarach 2x2 i 2x3 z losowymi liczbami całkowitymi od 1 do 10

In [10]:
macierz_2x2 = np.random.randint(1, 11, (2, 2))
macierz_2x3 = np.random.randint(1, 11, (2, 3))

Mnożenie macierzy

In [11]:
mnozenie_macierzy = np.dot(macierz_2x2, macierz_2x3)
print("Macierz 2x2:\n", macierz_2x2)
print("Macierz 2x3:\n", macierz_2x3)
print("Mnożenie macierzy 2x2 i 2x3:\n", mnozenie_macierzy)

Macierz 2x2:
 [[2 5]
 [1 6]]
Macierz 2x3:
 [[5 2 8]
 [5 5 2]]
Mnożenie macierzy 2x2 i 2x3:
 [[35 29 26]
 [35 32 20]]


# 8. Odwrócenie macierzy 3x3

Macierz 3x3 z losowymi liczbami całkowitymi od 1 do 10

In [12]:
macierz_3x3 = np.random.randint(1, 11, (3, 3))

Odwrócenie macierzy

In [13]:
if np.linalg.det(macierz_3x3) != 0:
    odwrocona_macierz_3x3 = np.linalg.inv(macierz_3x3)
    print("Macierz 3x3:\n", macierz_3x3)
    print("Odwrotność macierzy 3x3:\n", odwrocona_macierz_3x3)
else:
    print("Macierz 3x3 nie jest odwracalna:\n", macierz_3x3)

Macierz 3x3:
 [[8 5 8]
 [5 7 2]
 [1 4 4]]
Odwrotność macierzy 3x3:
 [[ 0.11494253  0.06896552 -0.26436782]
 [-0.10344828  0.13793103  0.13793103]
 [ 0.07471264 -0.15517241  0.17816092]]


# 9. Transpozycja macierzy 4x4

Macierz 4x4 z losowymi liczbami rzeczywistymi od 0 do 1

In [14]:
macierz_4x4 = np.random.rand(4, 4)

Transpozycja macierzy

In [15]:
transponowana_macierz_4x4 = macierz_4x4.T
print("Macierz 4x4:\n", macierz_4x4)
print("Transpozycja macierzy 4x4:\n", transponowana_macierz_4x4)

Macierz 4x4:
 [[0.05747828 0.12701671 0.26384018 0.4768735 ]
 [0.58855965 0.79380463 0.17282979 0.90519146]
 [0.93078385 0.16220754 0.34987601 0.37936862]
 [0.19662786 0.46281368 0.04676071 0.22174715]]
Transpozycja macierzy 4x4:
 [[0.05747828 0.58855965 0.93078385 0.19662786]
 [0.12701671 0.79380463 0.16220754 0.46281368]
 [0.26384018 0.17282979 0.34987601 0.04676071]
 [0.4768735  0.90519146 0.37936862 0.22174715]]


# 10. Mnożenie macierzy 3x4 przez wektor o rozmiarze 4

Macierz 3x4 i wektor o rozmiarze 4 z losowymi liczbami całkowitymi od 1 do 10

In [16]:
macierz_3x4 = np.random.randint(1, 11, (3, 4))
wektor_4 = np.random.randint(1, 11, 4)

Mnożenie macierzy przez wektor

In [17]:
mnozenie_macierzy_wektor = np.dot(macierz_3x4, wektor_4)
print("Macierz 3x4:\n", macierz_3x4)
print("Wektor 4:\n", wektor_4)
print("Mnożenie macierzy 3x4 przez wektor 4:\n", mnozenie_macierzy_wektor)

Macierz 3x4:
 [[8 7 5 5]
 [3 9 2 9]
 [3 2 6 9]]
Wektor 4:
 [8 8 2 3]
Mnożenie macierzy 3x4 przez wektor 4:
 [145 127  79]


# 11. Mnożenie macierzy 2x3 przez wektor o rozmiarze 3

Macierz 2x3 i wektor o rozmiarze 3 z losowymi liczbami rzeczywistymi od 0 do 1

In [18]:
macierz_2x3 = np.random.rand(2, 3)
wektor_3 = np.random.rand(3)

Mnożenie macierzy przez wektor

In [19]:
mnozenie_macierzy_wektor_2 = np.dot(macierz_2x3, wektor_3)
print("Macierz 2x3:\n", macierz_2x3)
print("Wektor 3:\n", wektor_3)
print("Mnożenie macierzy 2x3 przez wektor 3:\n", mnozenie_macierzy_wektor_2)

Macierz 2x3:
 [[0.47080418 0.41063709 0.76827395]
 [0.56631541 0.79305    0.50717971]]
Wektor 3:
 [0.84037952 0.98840086 0.63253343]
Mnożenie macierzy 2x3 przez wektor 3:
 [1.28748719 1.5805793 ]


# 12. Mnożenie pierwiastkowe dwóch macierzy 2x2

Dwie macierze 2x2 z losowymi liczbami całkowitymi od 1 do 10

In [20]:
macierz_2x2_1 = np.random.randint(1, 11, (2, 2))
macierz_2x2_2 = np.random.randint(1, 11, (2, 2))

Mnożenie pierwiastkowe (element-wise)

In [21]:
mnozenie_pierwiastkowe = macierz_2x2_1 * macierz_2x2_2
print("Macierz 2x2_1:\n", macierz_2x2_1)
print("Macierz 2x2_2:\n", macierz_2x2_2)
print("Mnożenie pierwiastkowe macierzy 2x2:\n", mnozenie_pierwiastkowe)

Macierz 2x2_1:
 [[10 10]
 [ 2  7]]
Macierz 2x2_2:
 [[10  2]
 [ 8 10]]
Mnożenie pierwiastkowe macierzy 2x2:
 [[100  20]
 [ 16  70]]


# 13. Iloczyn dwóch macierzy 2x2

Dwie macierze 2x2 z losowymi liczbami całkowitymi od 1 do 10

In [22]:
macierz_2x2_1 = np.random.randint(1, 11, (2, 2))
macierz_2x2_2 = np.random.randint(1, 11, (2, 2))

Iloczyn macierzy

In [23]:
iloczyn_macierzy = np.dot(macierz_2x2_1, macierz_2x2_2)
print("Macierz 2x2_1:\n", macierz_2x2_1)
print("Macierz 2x2_2:\n", macierz_2x2_2)
print("Iloczyn macierzy 2x2:\n", iloczyn_macierzy)

Macierz 2x2_1:
 [[9 7]
 [7 5]]
Macierz 2x2_2:
 [[7 8]
 [7 3]]
Iloczyn macierzy 2x2:
 [[112  93]
 [ 84  71]]


# 14. Suma elementów macierzy 5x5

 Macierz 5x5 z losowymi liczbami całkowitymi od 1 do 100

In [24]:
macierz_5x5 = np.random.randint(1, 101, (5, 5))

Suma elementów macierzy

In [25]:
suma_elementow = np.sum(macierz_5x5)
print("Macierz 5x5:\n", macierz_5x5)
print("Suma elementów macierzy 5x5:", suma_elementow)

Macierz 5x5:
 [[ 12  55 100  66  65]
 [ 78  50  70  80  67]
 [ 20   9  44  88  14]
 [ 70   5  51  39  68]
 [ 48  75  40  40  73]]
Suma elementów macierzy 5x5: 1327


# 15. Różnica dwóch macierzy 4x4

Dwie macierze 4x4 z losowymi liczbami całkowitymi od 1 do 10

In [26]:
macierz_4x4_1 = np.random.randint(1, 11, (4, 4))
macierz_4x4_2 = np.random.randint(1, 11, (4, 4))

Różnica macierzy

In [27]:
roznica_macierzy = macierz_4x4_1 - macierz_4x4_2
print("Macierz 4x4_1:\n", macierz_4x4_1)
print("Macierz 4x4_2:\n", macierz_4x4_2)
print("Różnica macierzy 4x4:\n", roznica_macierzy)

Macierz 4x4_1:
 [[ 2  8  8  7]
 [ 8  4  7  2]
 [ 1  1  8 10]
 [ 3  5 10  9]]
Macierz 4x4_2:
 [[ 3  2  5  5]
 [ 8  7  2 10]
 [ 3 10  5  7]
 [ 3  7  2  9]]
Różnica macierzy 4x4:
 [[-1  6  3  2]
 [ 0 -3  5 -8]
 [-2 -9  3  3]
 [ 0 -2  8  0]]


# 16. Suma elementów każdego wiersza macierzy 3x3

Macierz 3x3 z losowymi liczbami rzeczywistymi od 0 do 1

In [28]:
macierz_3x3 = np.random.rand(3, 3)

Wektor kolumnowy zawierający sumę elementów każdego wiersza

In [29]:
suma_wierszy = np.sum(macierz_3x3, axis=1)
print("Macierz 3x3:\n", macierz_3x3)
print("Suma elementów każdego wiersza:", suma_wierszy)

Macierz 3x3:
 [[0.48572515 0.43808077 0.28572458]
 [0.08528916 0.68824771 0.00185146]
 [0.27999881 0.44308949 0.04395428]]
Suma elementów każdego wiersza: [1.2095305  0.77538833 0.76704258]


# 17. Utworzenie macierzy z kwadratami liczb z innej macierzy

Macierz 3x4 z dowolnymi liczbami całkowitymi

In [30]:
macierz_3x4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

Macierz z kwadratami tych liczb

In [31]:
kwadraty_macierzy = macierz_3x4 ** 2
print("Macierz 3x4:\n", macierz_3x4)
print("Macierz z kwadratami tych liczb:\n", kwadraty_macierzy)

Macierz 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Macierz z kwadratami tych liczb:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


# 18. Wektor pierwiastków kwadratowych z liczb

Wektor o rozmiarze 4 z losowymi liczbami całkowitymi od 1 do 50

In [32]:
wektor_4 = np.random.randint(1, 51, 4)

Wektor pierwiastków kwadratowych

In [33]:
pierwiastki_wektora = np.sqrt(wektor_4)
print("Wektor 4:", wektor_4)
print("Pierwiastki kwadratowe wektora:", pierwiastki_wektora)

Wektor 4: [29 42 41 24]
Pierwiastki kwadratowe wektora: [5.38516481 6.4807407  6.40312424 4.89897949]
